import { writeFile } from "node:fs/promises";
import path from "node:path";
import { checkAiHealth, getPublicAiConfig } from "@/lib/analysis/openai";

type SetupBody = {
  apiKey?: string;
  baseUrl?: string;
  mode?: "fallback" | "always" | "off";
  model?: string;
  timeoutMs?: number;
};

export async function GET(request: Request) {
  const url = new URL(request.url);
  const includeHealth = url.searchParams.get("check") === "1";

  return Response.json({
    config: getPublicAiConfig(),
    health: includeHealth ? await checkAiHealth() : null,
  });
}

export async function POST(request: Request) {
  let body: SetupBody;

  try {
    body = (await request.json()) as SetupBody;
  } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const mode = body.mode === "always" || body.mode === "off" ? body.mode : "fallback";
  const baseUrl = cleanValue(body.baseUrl) || "http://localhost:11434/v1";
  const model = cleanValue(body.model) || "gemma4:e4b";
  const timeoutMs = Number.isFinite(body.timeoutMs) && Number(body.timeoutMs) >= 5000 ? Number(body.timeoutMs) : 120000;
  const apiKey = cleanValue(body.apiKey) ?? process.env.CRASHSENSE_AI_API_KEY ?? "";

  const env = [
    "# Generated by CrashSense AI UI setup.",
    "# Restart the dev server after editing this file manually.",
    `CRASHSENSE_AI_MODE=${mode}`,
    `CRASHSENSE_AI_BASE_URL=${baseUrl}`,
    `CRASHSENSE_AI_MODEL=${model}`,
    `CRASHSENSE_AI_API_KEY=${apiKey}`,
    `CRASHSENSE_AI_TIMEOUT_MS=${timeoutMs}`,
    "",
  ].join("\n");

  const envPath = path.join(process.cwd(), ".env.local");
  try {
    await writeFile(envPath, env, "utf8");
  } catch {
    return Response.json({ error: "Could not write .env.local. On hosted instances, configure environment variables in the host dashboard instead." }, { status: 500 });
  }

  process.env.CRASHSENSE_AI_MODE = mode;
  process.env.CRASHSENSE_AI_BASE_URL = baseUrl;
  process.env.CRASHSENSE_AI_MODEL = model;
  process.env.CRASHSENSE_AI_API_KEY = apiKey;
  process.env.CRASHSENSE_AI_TIMEOUT_MS = String(timeoutMs);

  return Response.json({
    config: getPublicAiConfig(),
    saved: true,
  });
}

function cleanValue(value: unknown): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }

  const trimmed = value.trim();

  return trimmed.length > 0 ? trimmed : undefined;
}
