import type { Confidence, LogType, RuleId } from "./types";

export type RuleDefinition = {
  id: RuleId;
  title: string;
  cause: string;
  summary: string;
  confidence: Confidence;
  patterns: string[];
  fixSteps: string[];
  appliesTo?: LogType[];
  specificity: number;
};

export const ruleDefinitions: RuleDefinition[] = [
  {
    id: "java-version-mismatch",
    title: "Java version mismatch",
    summary: "The log points to a Java runtime or bytecode version mismatch.",
    cause: "The app or modpack was built for a different Java version than the one currently running it.",
    confidence: "high",
    specificity: 10,
    appliesTo: ["minecraft", "unknown"],
    patterns: [
      "UnsupportedClassVersionError",
      "class file version \\d+",
      "compiled by a more recent version of the Java Runtime",
      "requires Java (?:version )?(?:17|21|22)",
      "Java \\d+ is required",
    ],
    fixSteps: [
      "Check the required Java version for the Minecraft/modpack version.",
      "Install the required Java runtime, usually Java 17 for modern 1.18-1.20 packs or Java 21 for newer packs.",
      "Update the launcher, container image, or PATH/JAVA_HOME so the required runtime is used.",
      "Restart and rerun the same log after confirming `java -version`.",
    ],
  },
  {
    id: "mod-loader-mismatch",
    title: "Mod loader mismatch",
    summary: "The log shows a Fabric, Forge, or NeoForge compatibility problem.",
    cause: "At least one mod appears to target a different loader or loader version than the current instance.",
    confidence: "high",
    specificity: 10,
    appliesTo: ["minecraft", "unknown"],
    patterns: [
      "Incompatible mod set",
      "requires (?:fabricloader|forge|neoforge)",
      "wrong mod loader",
      "only supports (?:Fabric|Forge|NeoForge)",
      "Mod File .* needs language provider",
      "Loading errors encountered.*(?:fabric|forge|neoforge)",
    ],
    fixSteps: [
      "Confirm whether the instance is Fabric, Forge, or NeoForge.",
      "Replace mods built for the wrong loader with matching versions.",
      "Check loader version requirements on the mod page.",
      "Remove one suspect mod at a time if the log lists several candidates.",
    ],
  },
  {
    id: "missing-dependency",
    title: "Missing dependency",
    summary: "A required dependency or companion mod is missing.",
    cause: "A mod, container, or app component depends on another package that is not installed or not visible at runtime.",
    confidence: "high",
    specificity: 9,
    patterns: [
      "missing (?:required )?(?:dependency|mod|library|module|package)",
      "requires .* but it is not installed",
      "Could not find required",
      "Cannot find module",
      "No module named",
      "depends on .* which is missing",
    ],
    fixSteps: [
      "Read the evidence line for the missing dependency name.",
      "Install the required dependency at the version requested by the failing component.",
      "For modpacks, download dependencies from the same loader and Minecraft version.",
      "Restart after clearing stale build or launcher caches if the dependency was recently added.",
    ],
  },
  {
    id: "duplicate-mod",
    title: "Duplicate mod",
    summary: "The log suggests the same mod or plugin is installed more than once.",
    cause: "Duplicate jar files or duplicate package definitions can make the loader abort startup.",
    confidence: "high",
    specificity: 10,
    appliesTo: ["minecraft", "unknown"],
    patterns: ["duplicate mod", "Mod .* is present multiple times", "DuplicateModsFound", "Found duplicate file", "same mod id"],
    fixSteps: [
      "Open the mods or plugins folder and sort by name.",
      "Remove older duplicate jars, especially files with copy suffixes or multiple versions.",
      "Keep only one version of each mod for the active loader and game version.",
      "Start again and confirm the duplicate warning is gone.",
    ],
  },
  {
    id: "mixin-error",
    title: "Mixin transformation error",
    summary: "A Minecraft mixin failed while modifying game or mod classes.",
    cause: "A mod is trying to patch code that does not match the loaded game, loader, or dependency versions.",
    confidence: "high",
    specificity: 9,
    appliesTo: ["minecraft", "unknown"],
    patterns: ["Mixin apply failed", "MixinTransformerError", "InjectionError", "Critical injection failure", "Mixin prepare failed"],
    fixSteps: [
      "Identify the mod named near the first mixin failure.",
      "Update that mod and its dependencies to versions matching the game and loader.",
      "Remove optimization or compatibility mods temporarily if the failing mixin target is unclear.",
      "Avoid mixing client-only performance mods into a server instance.",
    ],
  },
  {
    id: "bad-config-file",
    title: "Bad or corrupt config file",
    summary: "The log points to a malformed, unreadable, or incompatible configuration file.",
    cause: "A config file contains invalid syntax, stale options, or values from another app/mod version.",
    confidence: "medium",
    specificity: 8,
    patterns: ["Failed to load config", "ParsingException", "TOML parse error", "YAMLException", "Invalid config", "MalformedJsonException"],
    fixSteps: [
      "Back up the config file named in the evidence.",
      "Regenerate the config by moving it out of the active config directory.",
      "Reapply custom settings gradually after the app starts successfully.",
      "Check release notes for renamed or removed config options.",
    ],
  },
  {
    id: "client-server-mod-mismatch",
    title: "Client/server-only mod mismatch",
    summary: "The log suggests a client-only mod is on a server, or a server-only component is on the client.",
    cause: "The instance is loading a mod on the wrong side of the Minecraft runtime.",
    confidence: "high",
    specificity: 9,
    appliesTo: ["minecraft", "unknown"],
    patterns: ["Attempted to load class .* for invalid dist", "client-only", "server-only", "wrong side", "Dedicated server.*client"],
    fixSteps: [
      "Find the mod named near the invalid side warning.",
      "Remove client-only mods from dedicated servers.",
      "Keep server-only utilities out of client profiles unless the mod explicitly supports both sides.",
      "Use the modpack's server files when hosting a server.",
    ],
  },
  {
    id: "null-pointer-exception",
    title: "Java null pointer crash",
    summary: "A Java object was unexpectedly null, causing the app or mod to crash.",
    cause: "A mod or app component tried to use a value that was missing at runtime. In Minecraft logs, the first non-Minecraft stack frame usually points to the mod code or integration that needs attention.",
    confidence: "high",
    specificity: 9,
    appliesTo: ["minecraft", "unknown"],
    patterns: [
      "NullPointerException",
      "Cannot invoke .* because .* is null",
      "Cannot read field .* because .* is null",
      "because \".*\" is null",
    ],
    fixSteps: [
      "Find the first stack frame that is not from `net.minecraft`, `java.base`, Forge, Fabric, or NeoForge.",
      "Update or remove the mod named by that first external stack frame.",
      "If the crash happens when loading a world, back up the world and test with the suspect mod disabled.",
      "Report the crash to the mod author with the full stack trace and the exact Minecraft, loader, and mod versions.",
    ],
  },
  {
    id: "permission-denied",
    title: "Permission denied",
    summary: "The process failed because it could not access a required file, directory, device, or socket.",
    cause: "The runtime user does not have enough permissions for the path or resource named in the log.",
    confidence: "high",
    specificity: 8,
    patterns: ["permission denied", "EACCES", "access is denied", "operation not permitted"],
    fixSteps: [
      "Identify the path or resource in the evidence line.",
      "Fix ownership and permissions for the runtime user, not just your interactive user.",
      "For Docker or Unraid, verify volume mappings, PUID/PGID, and host path permissions.",
      "Restart the service after applying the permission change.",
    ],
  },
  {
    id: "uid-gid-mismatch",
    title: "Docker PUID/PGID mismatch",
    summary: "A container appears to be running with user or group IDs that do not match the mounted files.",
    cause: "The container user cannot read or write mounted host paths because PUID/PGID or ownership is wrong.",
    confidence: "medium",
    specificity: 8,
    appliesTo: ["docker", "unknown"],
    patterns: ["PUID", "PGID", "user id .* permission", "group id .* permission", "chown .* not permitted"],
    fixSteps: [
      "Check the PUID and PGID values configured for the container.",
      "Match those IDs to the owner of the host directories being mounted.",
      "Fix host path ownership recursively only on the intended app data directory.",
      "Restart the container and confirm it can write config and logs.",
    ],
  },
  {
    id: "out-of-memory",
    title: "Out of memory",
    summary: "The log contains an out-of-memory failure.",
    cause: "The process exhausted its memory limit or Java heap allocation.",
    confidence: "high",
    specificity: 9,
    patterns: ["OutOfMemoryError", "Java heap space", "Cannot allocate memory", "Killed process .* out of memory", "container killed due to memory usage", "exit code 137"],
    fixSteps: [
      "Increase the memory limit for the process, container, or CI job.",
      "For Java apps, set a realistic `-Xmx` value below the host/container limit.",
      "Close competing workloads or reduce modpack/server load.",
      "If the issue repeats, capture memory usage around startup to find the spike.",
    ],
  },
  {
    id: "port-in-use",
    title: "Port already in use",
    summary: "The app could not bind to a network port because something else is already using it.",
    cause: "Another process or container is bound to the same host port.",
    confidence: "high",
    specificity: 9,
    patterns: ["address already in use", "EADDRINUSE", "port .* already in use", "bind.*(?:failed|failure).*in use", "port is already allocated"],
    fixSteps: [
      "Find which process or container is using the port.",
      "Stop the conflicting service or change one of the port mappings.",
      "For Docker, check both container port and host port mappings.",
      "Restart the service and confirm the bind error no longer appears.",
    ],
  },
  {
    id: "path-not-found",
    title: "File path not found",
    summary: "The log references a missing file or directory.",
    cause: "A configured path, mounted volume, working directory, or generated artifact does not exist at runtime.",
    confidence: "medium",
    specificity: 7,
    patterns: ["No such file or directory", "ENOENT", "file not found", "path not found", "Cannot find path", "does not exist"],
    fixSteps: [
      "Check the exact missing path from the evidence line.",
      "Create the directory or correct the configured path.",
      "For containers, verify the host path exists before it is mounted.",
      "For CI, ensure the artifact is generated before later steps reference it.",
    ],
  },
  {
    id: "gpu-nvidia-not-detected",
    title: "GPU or NVIDIA runtime not detected",
    summary: "The log indicates NVIDIA GPU access is unavailable.",
    cause: "The app expected an NVIDIA GPU, driver, or container runtime, but the runtime cannot see it.",
    confidence: "high",
    specificity: 10,
    appliesTo: ["docker", "unknown"],
    patterns: ["nvidia-smi.*not found", "No NVIDIA GPU detected", "could not select device driver.*gpu", "CUDA driver.*not found", "libcuda\\.so.*(?:not found|cannot open)", "NVIDIA-SMI has failed"],
    fixSteps: [
      "Confirm the host can see the GPU with `nvidia-smi`.",
      "Install or repair the NVIDIA driver on the host.",
      "For Docker or Unraid, configure the NVIDIA container runtime and pass GPU access into the container.",
      "Restart the container after confirming the runtime exposes the GPU device.",
    ],
  },
  {
    id: "docker-volume-mapping",
    title: "Docker volume mapping problem",
    summary: "The log suggests a host path or bind mount is missing or mapped incorrectly.",
    cause: "A container path points to the wrong host directory, a missing host path, or a read-only mount.",
    confidence: "medium",
    specificity: 8,
    appliesTo: ["docker", "unknown"],
    patterns: ["invalid mount config", "bind source path does not exist", "read-only file system", "mount .* denied", "not a directory"],
    fixSteps: [
      "Inspect the container volume mappings and compare host paths with container paths.",
      "Create missing host directories before starting the container.",
      "Remove accidental read-only flags for paths the app must write.",
      "On Unraid, confirm the mapped share exists and has the expected case-sensitive path.",
    ],
  },
  {
    id: "dns-failure",
    title: "DNS or network resolution failure",
    summary: "The runtime cannot resolve a hostname or reach a network dependency.",
    cause: "DNS, network configuration, or outbound access is failing for the process/container/runner.",
    confidence: "medium",
    specificity: 7,
    patterns: ["ENOTFOUND", "EAI_AGAIN", "Temporary failure in name resolution", "Could not resolve host", "Name or service not known"],
    fixSteps: [
      "Check whether the host can resolve the same domain.",
      "For containers, verify DNS settings and network mode.",
      "For CI, retry transient DNS failures before changing code.",
      "Pin a working registry or mirror only if the upstream DNS issue is persistent.",
    ],
  },
  {
    id: "image-pull-failure",
    title: "Container image pull failure",
    summary: "Docker could not pull the configured image.",
    cause: "The image name, tag, credentials, or registry availability is wrong.",
    confidence: "high",
    specificity: 9,
    appliesTo: ["docker", "github-actions", "unknown"],
    patterns: ["pull access denied", "manifest unknown", "repository does not exist", "failed to pull image", "unauthorized: authentication required"],
    fixSteps: [
      "Check the image repository and tag for typos.",
      "Confirm the registry credentials are available to Docker or the CI runner.",
      "Try pulling the image manually from the same host.",
      "Use a pinned known-good tag instead of `latest` if the upstream changed.",
    ],
  },
  {
    id: "healthcheck-failure",
    title: "Container healthcheck failure",
    summary: "The service is starting but failing its healthcheck.",
    cause: "The app inside the container is not becoming ready on the expected port, path, or startup window.",
    confidence: "medium",
    specificity: 8,
    appliesTo: ["docker", "unknown"],
    patterns: ["unhealthy", "healthcheck failed", "Health check exceeded timeout", "container .* is unhealthy"],
    fixSteps: [
      "Read the container logs before the healthcheck failure.",
      "Confirm the healthcheck port and path match the app's actual listener.",
      "Increase the healthcheck start period if initialization is slow.",
      "Fix the app startup error before tuning the healthcheck.",
    ],
  },
  {
    id: "github-actions-missing-secret",
    title: "GitHub Actions secret missing",
    summary: "A workflow appears to be missing a required secret or token.",
    cause: "The workflow references a secret that is not configured for this repository, environment, or fork context.",
    confidence: "high",
    specificity: 9,
    appliesTo: ["github-actions", "unknown"],
    patterns: ["secrets\\.[A-Z0-9_]+", "secret.*not found", "Input required and not supplied", "Resource not accessible by integration"],
    fixSteps: [
      "Check the workflow step for the missing input or secret name.",
      "Add the secret in repository or environment settings.",
      "For pull requests from forks, avoid workflows that require privileged secrets.",
      "Confirm the job has the permissions it needs in the workflow `permissions` block.",
    ],
  },
  {
    id: "github-checkout-failure",
    title: "GitHub checkout failure",
    summary: "The workflow failed while checking out repository contents.",
    cause: "The checkout step could not fetch the requested ref, submodule, or repository with the available credentials.",
    confidence: "medium",
    specificity: 8,
    appliesTo: ["github-actions", "unknown"],
    patterns: ["actions/checkout", "fatal: repository .* not found", "fatal: couldn't find remote ref", "submodule .* failed", "detected dubious ownership"],
    fixSteps: [
      "Confirm the branch, tag, or SHA exists.",
      "Check whether private submodules require a token with access.",
      "Update `actions/checkout` configuration for submodules if needed.",
      "For self-hosted runners, clean stale workspace ownership issues.",
    ],
  },
  {
    id: "runtime-version-mismatch",
    title: "Runtime version mismatch",
    summary: "The log suggests the job is using the wrong Node, Python, Java, or package runtime version.",
    cause: "Dependencies or build tooling require a different runtime than the one configured in CI or the container.",
    confidence: "medium",
    specificity: 8,
    appliesTo: ["github-actions", "docker", "unknown"],
    patterns: ["The engine .* is incompatible", "requires Node\\.js", "Unsupported engine", "Python .* is not supported", "requires Python", "Gradle .* requires Java"],
    fixSteps: [
      "Check the required runtime version in package metadata or tool docs.",
      "Update the CI setup action, Docker base image, or local runtime.",
      "Commit lockfile changes only after reinstalling with the intended runtime.",
      "Print the runtime version in CI to verify the fix.",
    ],
  },
  {
    id: "dependency-cache-corruption",
    title: "Dependency cache corruption",
    summary: "The failure looks like a stale or corrupt dependency cache.",
    cause: "The package manager restored cached files that no longer match the lockfile or runtime.",
    confidence: "medium",
    specificity: 7,
    appliesTo: ["github-actions", "unknown"],
    patterns: ["cache hit", "integrity checksum failed", "EINTEGRITY", "Unexpected end of JSON input", "lockfile.*out of date", "Cannot find package.*node_modules"],
    fixSteps: [
      "Clear the dependency cache for the failing branch or runner.",
      "Reinstall from the lockfile with a clean package manager cache.",
      "Include runtime and lockfile hashes in the cache key.",
      "Avoid caching generated build output as dependencies.",
    ],
  },
  {
    id: "generic-crash",
    title: "Generic crash",
    summary: "The log shows a crash, but no specific known signature was detected.",
    cause: "The failure needs a closer read of the stack trace or surrounding configuration.",
    confidence: "low",
    specificity: 1,
    patterns: ["exception", "fatal", "crash", "failed", "error"],
    fixSteps: [
      "Look for the first error line, not just the final shutdown message.",
      "Check recent config, dependency, image, or mod changes.",
      "Rerun with debug logging if the current log omits the root error.",
      "Share the full log and environment details when opening an issue.",
    ],
  },
];
