import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { spawnSync } from "node:child_process";

const args = new Set(process.argv.slice(2));
const envPath = ".env.local";
const defaultModel = process.env.CRASHSENSE_AI_MODEL || "gemma4:e4b";

const presets = {
  local: {
    mode: "fallback",
    baseUrl: "http://localhost:11434/v1",
    model: defaultModel,
    apiKey: "",
  },
  api: {
    mode: "fallback",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4o-mini",
    apiKey: "replace-me",
  },
  rules: {
    mode: "off",
    baseUrl: "http://localhost:11434/v1",
    model: defaultModel,
    apiKey: "",
  },
};

const selectedPreset = args.has("--api") ? "api" : args.has("--rules-only") ? "rules" : args.has("--local") || args.has("--yes") ? "local" : undefined;

if (args.has("--help")) {
  printHelp();
  process.exit(0);
}

const presetName = selectedPreset ?? (await promptForPreset());
const preset = presets[presetName];
await writeEnv(preset);

console.log("");
console.log(`Created ${envPath} with the ${presetName} setup.`);

if (presetName === "local") {
  if (!hasOllama()) {
    printOllamaInstallMessage();
  } else if (args.has("--skip-model")) {
    console.log(`Skipped model pull. Run this later: npm run ai:ollama:pull`);
  } else {
    console.log(`Pulling local model: ${preset.model}`);
    run("ollama", ["pull", preset.model]);
  }
}

if (presetName === "api") {
  console.log("");
  console.log("Edit .env.local and replace CRASHSENSE_AI_API_KEY=replace-me with your provider API key.");
}

console.log("");
console.log("Next steps:");
if (presetName === "local") {
  console.log("  1. If Ollama was just installed, close and reopen your terminal.");
  console.log("  2. Confirm Ollama works: ollama --version");
  console.log("  3. Pull the model if needed: npm run ai:ollama:pull");
  console.log("  4. Start CrashSense AI: npm run dev");
  console.log("  5. Open http://localhost:3000");
} else if (presetName === "api") {
  console.log("  1. Edit .env.local and add your API key.");
  console.log("  2. Start CrashSense AI: npm run dev");
  console.log("  3. Open http://localhost:3000");
} else {
  console.log("  1. Start CrashSense AI: npm run dev");
  console.log("  2. Open http://localhost:3000");
}

async function promptForPreset() {
  if (!input.isTTY) {
    return "local";
  }

  const rl = createInterface({ input, output });
  console.log("CrashSense AI setup");
  console.log("");
  console.log("Choose an AI setup:");
  console.log("  1. Local AI with Ollama + Gemma 4 (recommended)");
  console.log("  2. Remote OpenAI-compatible API key");
  console.log("  3. Rules only, no AI");
  console.log("");

  const answer = (await rl.question("Select 1, 2, or 3: ")).trim();
  rl.close();

  if (answer === "2") {
    return "api";
  }

  if (answer === "3") {
    return "rules";
  }

  return "local";
}

async function writeEnv(preset) {
  if (existsSync(envPath) && !args.has("--force")) {
    console.log(`${envPath} already exists. Keeping it unchanged.`);
    console.log("Use `npm run setup -- --force` to regenerate it.");
    return;
  }

  await writeFile(
    envPath,
    [
      "# Generated by `npm run setup`.",
      "# Edit these values if you want to change AI provider, model, or mode.",
      "",
      "# fallback = use AI only when no specific rule matches",
      "# always = use AI to enrich every result",
      "# off = never call AI",
      `CRASHSENSE_AI_MODE=${preset.mode}`,
      `CRASHSENSE_AI_BASE_URL=${preset.baseUrl}`,
      `CRASHSENSE_AI_MODEL=${preset.model}`,
      `CRASHSENSE_AI_API_KEY=${preset.apiKey}`,
      "CRASHSENSE_AI_TIMEOUT_MS=120000",
      "",
    ].join("\n"),
  );
}

function hasOllama() {
  const result = spawnSync("ollama", ["--version"], { stdio: "ignore", shell: process.platform === "win32" });

  return result.status === 0;
}

function run(command, commandArgs) {
  const result = spawnSync(command, commandArgs, { stdio: "inherit", shell: process.platform === "win32" });

  if (result.status !== 0) {
    console.log("");
    console.log(`Command failed: ${command} ${commandArgs.join(" ")}`);
    console.log("You can retry later with: npm run ai:ollama:pull");
  }
}

function printOllamaInstallMessage() {
  console.log("");
  console.log("Ollama is not installed or is not available on PATH.");
  console.log("Install it here: https://ollama.com/download");
  console.log("");
  console.log("After installing:");
  console.log("  1. Close and reopen your terminal.");
  console.log("  2. Run: ollama --version");
  console.log("  3. Run: npm run ai:ollama:pull");
}

function printHelp() {
  console.log(
    [
      "CrashSense AI setup",
      "",
      "Usage:",
      "  npm run setup",
      "  npm run setup:local",
      "  npm run setup:api",
      "  npm run setup:rules",
      "",
      "Options:",
      "  --force       overwrite .env.local",
      "  --skip-model  do not pull the Ollama model",
      "  --yes         use local Ollama + Gemma 4 defaults",
    ].join("\n"),
  );
}
